// Auto-generated by generate_swing_lut.py — DO NOT EDIT
#pragma once
#include <cstddef>

// One entry in the arm-swing lookup table.
// fwd/bck hold 200 elbow angles in rad on a uniform phase grid [0,1].
struct SwingEntry {
    float        period_s;
    const float* fwd;         // forward-half trajectory (rad, 200 pts)
    std::size_t  fwd_len;
    float        fwd_dur_s;   // real-time duration of forward half
    const float* bck;         // back-half trajectory (rad, 200 pts)
    std::size_t  bck_len;
    float        bck_dur_s;   // real-time duration of back half
};

// 26 entries (6 measured + 20 cubic-spline interpolated),
// ordered by period_s ascending.
extern const SwingEntry SWING_LUT[26];
extern const std::size_t SWING_LUT_SIZE;

// Returns the SwingEntry whose period_s is closest to `detected_period_s`.
const SwingEntry& swing_lut_lookup(float detected_period_s);
