// Auto-generated by generate_swing_lut.py — DO NOT EDIT
#pragma once
#include <cstddef>

// One entry in the arm-swing lookup table.
//
// fwd/bck are physical-time arrays sampled at 100 Hz.
// Array length = round(duration_s * 100), so index i → real time i / 100.0 s.
// Angles are stored in rad.
//
// To play back at the correct speed, step through the array at
// one entry per controller tick (assumed 100 Hz).
struct SwingEntry {
    float        period_s;
    const float* fwd;         // forward-half trajectory (rad, 100 Hz)
    std::size_t  fwd_len;     // number of samples = round(fwd_dur_s * HZ)
    float        fwd_dur_s;   // real-time duration of forward half
    const float* bck;         // back-half trajectory (rad, 100 Hz)
    std::size_t  bck_len;     // number of samples = round(bck_dur_s * HZ)
    float        bck_dur_s;   // real-time duration of back half
};

// 26 entries (6 measured + 20 cubic-spline interpolated),
// ordered by period_s ascending.
extern const SwingEntry SWING_LUT[26];
extern const std::size_t SWING_LUT_SIZE;

// Returns the SwingEntry whose period_s is closest to `detected_period_s`.
const SwingEntry& swing_lut_lookup(float detected_period_s);
